apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dept
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: mysql
          image: jbergstroem/mariadb-alpine
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
            - name: MYSQL_DATABASE
              value: "db"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
      volumes:
        - name: mysql-persistent-storage
          hostPath:
            # directory location on host
            path: /home/eramax/kubesvs/mysql
            # this field is optional
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-srv
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30306
  type: NodePort
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-dep
  labels:
    app: mvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvc-app
  template:
    metadata:
      labels:
        app: mvc-app
    spec:
      containers:
      - name: mvc-app
        image: eramax/mvc-k8s-sample:v2.#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=mysql-srv;database=db;user=root;password=123;port=3306;SSL Mode=None;
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-srv
spec:
  selector:
    app: mvc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31111
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mvc1-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.frontend.rule.type: PathPrefixStrip
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  rules:
  - host: mvc.app.eramax.net
    http:
      paths:
      - path: /
        backend:
          serviceName: mvc-srv
          servicePort: 80
  tls:
  - hosts:
    - k8.eramax.net
    secretName: k8-eramax-net-tls
