apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dept
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: jbergstroem/mariadb-alpine
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123"
            - name: MYSQL_DATABASE
              value: "db"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-srv
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30306
  type: NodePort
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvc-dep
  labels:
    app: mvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvc-app
  template:
    metadata:
      labels:
        app: mvc-app
    spec:
      containers:
      - name: mvc-app
        image: eramax/mvc-k8s-sample:v2.#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__DefaultConnection
          value: Server=mysql-srv;database=db;user=root;password=123;port=3306;SSL Mode=None;
---
apiVersion: v1
kind: Service
metadata:
  name: mvc-srv
spec:
  selector:
    app: mvc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30112
  type: NodePort